### ISSUE TITLE
Add function "amount in words"

### ISSUE THREAD

**Issue by Oalf72** [navferty/NavfertyExcelAddIn#48] opened 2020-05-30 11:04 UTC
Add function "amount in words"

The idea is based on the need to write down the amount in words in contracts and payments.

Highly likely as is https://micro-solution.ru/projects/addin_vba-excel/summ_words
https://github.com/maestrow/amount-in-words
https://github.com/javadev/moneytostr-russian/blob/master/src/main/cs/MoneyToStr.cs
https://www.cyberforum.ru/vba/thread1463280.html

**Comment by navferty** [comment] 2020-05-30 11:21
@Oalf72  Is that what you neaded?
https://github.com/navferty/NavfertyExcelAddIn/issues/42

Feature was implemented yesterday =)

**Comment by Oalf72** [comment] 2020-06-01 13:03
tnx

**Comment by navferty** [comment] 2020-06-02 19:47
Duplicate of #42

**Closed by navferty** 2020-06-02 19:47 UTC
